FROM archlinux-gui-devel:1.3.0

# Update repository and system.
RUN pacman -Syu --noconfirm

# Install Monospace fonts.
RUN pacman -S ttf-jetbrains-mono ttf-0xproto-nerd --noconfirm

# Install VSCode.
RUN su aur -c 'yay -S --noconfirm visual-studio-code-bin'

# Create a shell script to start and wait for VSCode
RUN echo '#!/bin/bash' > /root/start-and-wait-vscode.sh && \
    echo 'dbus-run-session code --no-sandbox --user-data-dir /root/.config/Code' >> /root/start-and-wait-vscode.sh && \
    echo 'while ! pgrep -x "code" > /dev/null; do sleep 1; done' >> /root/start-and-wait-vscode.sh && \
    echo 'while pgrep -x code > /dev/null; do sleep 1; done' >> /root/start-and-wait-vscode.sh

RUN chmod +x /root/start-and-wait-vscode.sh

# Start vscode
CMD /root/start-and-wait-vscode.sh
