FROM archlinux-gui-devel:1.2.0

# Update repository and system.
RUN pacman -Syu --noconfirm

# Install Monospace fonts and VSCode.
RUN pacman -S ttf-jetbrains-mono ttf-0xproto-nerd code --noconfirm

COPY asset/start-and-wait-vscode.sh /root/start-and-wait-vscode.sh

RUN chmod +x /root/start-and-wait-vscode.sh

# Start vscode
# CMD dbus-run-session code --no-sandbox
CMD /root/start-and-wait-vscode.sh
