FROM archlinux-gui-devel:1.3.0

# Update repository and system.
RUN pacman -Syu --noconfirm

# Install Monospace fonts.
RUN pacman -S ttf-jetbrains-mono ttf-0xproto-nerd --noconfirm

# Install JetBrains CLion.
RUN su aur -c 'yay --noconfirm -S clion clion-jre clion-cmake clion-gdb'

# Start CLion
CMD dbus-run-session clion
